replicaCount: 2
image:
  repository: nginx
  tag: alpine
service:
  type: ClusterIP
  port: 80
ingress:
  enabled: true
  className: nginx
  host: icneo-nginx.local
  # Drupal PostgreSQL Instance Configuration
drupalPg:
  enabled: true
  replicaCount: 1
  image:
    repository: library/drupal
    tag: 10.6.12-php8.3-apache-bookworm
    pullPolicy: IfNotPresent
  contextPath: /mydrupal
  ingress:
    host: pg-drupal.local
  database:
    host: host.docker.internal  # Change to host.minikube.internal if using Minikube
    name: drupaldb
    user: drupaldb_usr
    password: drupaldb_usr