replicaCount: 2
image:
  repository: nginx
  tag: alpine
service:
  type: ClusterIP
  port: 80
ingress:
  enabled: true
  className: nginx
  host: icneo-nginx.local
  # Drupal PostgreSQL Instance Configuration
drupalPg:
  enabled: true
  replicaCount: 1
  image:
    repository: library/drupal
    tag: 10.4-apache  # 🌟 Back to built-in Apache server on Port 80
    pullPolicy: IfNotPresent
  contextPath: /mydrupal
  ingress:
    host: pg-drupal.local
  database:
    host: host.docker.internal
    name: drupaldb
    user: drupaldb_usr
    password: drupaldb_usr